### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): M

### ISSUE THREAD

**Issue by KangChou** [yzhangcs/parser#105]
python3+ubuntu

test:
```python
from supar import Parser
parser = Parser.load('biaffine-dep-en')
dataset = parser.predict('I saw Sarah with a telescope.', lang='en', prob=True, verbose=False)
print(dataset)
```
![image](https://user-images.githubusercontent.com/36963108/171564741-dcd2f6be-e835-45f8-917e-3336436a2081.png)

```bash

python supar_demo.py 
/opt/conda/lib/python3.6/site-packages/torch/hub.py:452: UserWarning: Falling back to the old format < 1.6. This support will be deprecated in favor of default zipfile format introduced in 1.6. Please redo torch.save() to save it in the new zipfile format.
  warnings.warn('Falling back to the old format < 1.6. This support will be '








Downloading https://nlp.stanford.edu/software/stanza/stanza-resources//resources_1.4.0.json: 100%|██████████████████████████████████████████████| 154k/154k [00:01<00:00, 109kB/s]
2022-06-02 06:08:02 INFO Downloading default packages for language: en (English)...
2022-06-02 06:08:06 INFO File exists: /root/stanza_resources/en/default.zip
2022-06-02 06:08:28 INFO Finished downloading models and saved to /root/stanza_resources.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9e860c1048>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /stanfordnlp/stanza-resources/main/resources_1.4.0.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e860c1048>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/supar/utils/tokenizer.py", line 9, in __init__
    self.pipeline = stanza.Pipeline(lang=lang, processors='tokenize', tokenize_no_ssplit=True)
  File "/opt/conda/lib/python3.6/site-packages/stanza/pipeline/core.py", line 192, in __init__
    proxies=proxies)
  File "/opt/conda/lib/python3.6/site-packages/stanza/resources/common.py", line 436, in download_resources_json
    raise_for_status=True
  File "/opt/conda/lib/python3.6/site-packages/stanza/resources/common.py", line 147, in request_file
    download_file(url, temppath, proxies, raise_for_status)
  File "/opt/conda/lib/python3.6/site-packages/stanza/resources/common.py", line 109, in download_file
    r = requests.get(url, stream=True, proxies=proxies)
  File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /stanfordnlp/stanza-resources/main/resources_1.4.0.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e860c1048>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9e860d6860>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /stanfordnlp/stanza-resources/main/resources_1.4.0.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e860d6860>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "supar_demo.py", line 10, in <module>
    dataset = parser.predict('I saw Sarah with a telescope.', lang='en', prob=True, verbose=False)
  File "/opt/conda/lib/python3.6/site-packages/supar/parsers/dependency.py", line 136, in predict
    return super().predict(**Config().update(locals()))
  File "/opt/conda/lib/python3.6/site-packages/supar/parsers/parser.py", line 109, in predict
    dataset = Dataset(self.transform, data, lang=lang)
  File "/opt/conda/lib/python3.6/site-packages/supar/utils/data.py", line 40, in __init__
    self.sentences = transform.load(data, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/supar/utils/transform.py", line 374, in load
    tokenizer = Tokenizer(lang)
  File "/opt/conda/lib/python3.6/site-packages/supar/utils/tokenizer.py", line 12, in __init__
    self.pipeline = stanza.Pipeline(lang=lang, processors='tokenize', tokenize_no_ssplit=True)
  File "/opt/conda/lib/python3.6/site-packages/stanza/pipeline/core.py", line 192, in __init__
    proxies=proxies)
  File "/opt/conda/lib/python3.6/site-packages/stanza/resources/common.py", line 436, in download_resources_json
    raise_for_status=True
  File "/opt/conda/lib/python3.6/site-packages/stanza/resources/common.py", line 147, in request_file
    download_file(url, temppath, proxies, raise_for_status)
  File "/opt/conda/lib/python3.6/site-packages/stanza/resources/common.py", line 109, in download_file
    r = requests.get(url, stream=True, proxies=proxies)
  File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /stanfordnlp/stanza-resources/main/resources_1.4.0.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e860d6860>: Failed to establish a new connection: [Errno 111] Connection refused',))


```

**Comment by yzhangcs** [comment]
@KangChou Hi, this does not seem to be a bug of `SuPar`. You might wish to find a solution from [stanza](https://github.com/stanfordnlp/stanza/issues).
