### ISSUE TITLE
the checkpoint of 'biaffine-dep-roberta-en' is unavailable

### ISSUE THREAD

**Issue by yisu0** [yzhangcs/parser#112]
as the title

**Comment by yisu0** [comment]
Thanks, it has been solved, there were some problems of the network.

**Comment by YeJinPaark** [comment]
what's the problems of the network?

I have the same issue like that

>>> from supar import Parser
>>> parser=Parser.load('biaffine-dep-roberta-en')
Downloading biaffine-dep-roberta-en to /root/.cache/supar/biaffine-dep-roberta-en
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/supar/utils/fn.py", line 335, in download
    torch.hub.download_url_to_file(url, path, progress=True)
  File "/opt/conda/lib/python3.10/site-packages/torch/hub.py", line 610, in download_url_to_file
    req = Request(url, headers={"User-Agent": "torch.hub"})
  File "/opt/conda/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/opt/conda/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/opt/conda/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'biaffine-dep-roberta-en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/supar/parser.py", line 564, in load
    path = download(supar.MODEL[src].get(path, path), reload=reload)
  File "/opt/conda/lib/python3.10/site-packages/supar/utils/parallel.py", line 32, in wrapper
    value = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/supar/utils/fn.py", line 337, in download
    raise RuntimeError(f"File {url} unavailable. Please try other sources.")
RuntimeError: File biaffine-dep-roberta-en unavailable. Please try other sources.

**Comment by yzhangcs** [comment]
@YeJinPaark Hi, if the pkg is installed from src, you may need to download the model with the name `dep-biaffine-roberta-en`

**Comment by lxin1997** [comment]
您好，我运行了如下代码：
pip install -U supar
from supar import Parser
parser = Parser.load('dep-biaffine-en')
错误信息为：ValueError: unknown url type: 'dep-biaffine-en'
我是需要将这个模型手动下载吗？如果需要的话，可以提供本模型的url吗？
@yzhangcs

**Comment by yzhangcs** [comment]
@lxin1997 目前最新的代码对模型的名称有点更改，可以不用管，目前已经release最高版本为1.1.4，可以使用`biaffine-dep-en`这个名字

**Comment by lxin1997** [comment]
好的，谢谢！另外，能否提供一下常用邮箱，有点nlp方向的小问题想向您咨询一下。如有打扰，还请原谅

**Comment by yzhangcs** [comment]
@lxin1997 邮箱[主页](https://github.com/yzhangcs)有哈

**Comment by yzhangcs** [comment]
@YeJinPaark 
```py
Parser.load('dep-biaffine-roberta-en')
```
