### ISSUE TITLE
unexpected keyword argument 'defaults'

### ISSUE THREAD

**Issue by attardi** [yzhangcs/parser#24]
Running:

python run.py -h

I get:

I0519 11:18:48.137495 139755282601792 file_utils.py:55] TensorFlow version 2.1.0 available.
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from parser.cmds import Evaluate, Predict, Train
  File "/project/piqasso/tools/biaffine-parser/parser/cmds/__init__.py", line 3, in <module>
    from .evaluate import Evaluate
  File "/project/piqasso/tools/biaffine-parser/parser/cmds/evaluate.py", line 5, in <module>
    from parser.cmds.cmd import CMD
  File "/project/piqasso/tools/biaffine-parser/parser/cmds/cmd.py", line 4, in <module>
    from parser.utils import Embedding
  File "/project/piqasso/tools/biaffine-parser/parser/utils/__init__.py", line 3, in <module>
    from . import corpus, data, field, fn, metric
  File "/project/piqasso/tools/biaffine-parser/parser/utils/corpus.py", line 10, in <module>
    defaults=[None]*10)
TypeError: namedtuple() got an unexpected keyword argument 'defaults'

**Comment by attardi** [comment]
Solution for Python 3.6

In parser/utils/corpus.py:

CoNLL = namedtuple(typename='CoNLL',
                   field_names=['ID', 'FORM', 'LEMMA', 'CPOS', 'POS',
                                'FEATS', 'HEAD', 'DEPREL', 'PHEAD', 'PDEPREL'],
                   ) # defaults=[None]*10)                                      
CoNLL.__new__.__defaults__ = (None,) * 10

**Comment by yzhangcs** [comment]
Python 3.7 works.
And if you only care about training, directly delete this line.
