### ISSUE TITLE
TypeError: 'builtin_function_or_method' object is not subscriptable

### ISSUE THREAD

**Issue by unikcc** [yzhangcs/parser#80]
Dalao SOS, I just run         

```
loss, metric = Parser.load('crf2o-dep-en').evaluate('ptb/test.conllx', verbose=False)
```
and it throws 

```
Traceback (most recent call last):
  File "/pycharmProjects/temp/temp.py", line 32, in <module>
    template = Template()
  File "/pycharmProjects/temp/temp.py", line 24, in __init__
    loss, metric = Parser.load('crf2o-dep-en').evaluate('ptb/test.conllx', verbose=False)
  File "/.miniconda3/envs/supar/lib/python3.7/site-packages/supar/parsers/dep.py", line 620, in evaluate
    return super().evaluate(**Config().update(locals()))
  File "/.miniconda3/envs/supar/lib/python3.7/site-packages/supar/parsers/dep.py", line 90, in evaluate
    return super().evaluate(**Config().update(locals()))
  File ".miniconda3/envs/supar/lib/python3.7/site-packages/supar/parsers/parser.py", line 109, in evaluate
    dataset.build(batch_size, buckets)
  File "/.miniconda3/envs/supar/lib/python3.7/site-packages/supar/utils/data.py", line 79, in build
    fields = self.transform(self.sentences)
  File "/.miniconda3/envs/supar/lib/python3.7/site-packages/supar/utils/transform.py", line 41, in __call__
    sentence.transformed[f.name] = f.transform([getattr(sentence, f.name)])[0]
  File "/.miniconda3/envs/supar/lib/python3.7/site-packages/supar/utils/field.py", line 372, in transform
    charts = [torch.cat((torch.empty_like[:1].fill_(self.bos_index), chart), -1) for chart in charts]
  File "/.miniconda3/envs/supar/lib/python3.7/site-packages/supar/utils/field.py", line 372, in <listcomp>
    charts = [torch.cat((torch.empty_like[:1].fill_(self.bos_index), chart), -1) for chart in charts]
TypeError: 'builtin_function_or_method' object is not subscriptable
```

My package version: 
```
certifi            2021.5.30
charset-normalizer 2.0.4
click              8.0.1
dill               0.3.4
filelock           3.0.12
huggingface-hub    0.0.16
idna               3.2
importlib-metadata 4.8.1
joblib             1.0.1
nltk               3.6.2
numpy              1.21.2
packaging          21.0
Pillow             8.3.1
pip                21.0.1
protobuf           3.17.3
pyparsing          2.4.7
PyYAML             5.4.1
regex              2021.8.28
requests           2.26.0
sacremoses         0.0.45
setuptools         52.0.0.post20210125
six                1.16.0
stanza             1.2.3
supar              1.1.2
tokenizers         0.10.3
torch              1.9.0+cu111
torchaudio         0.9.0
torchvision        0.10.0+cu111
tqdm               4.62.2
transformers       4.10.0
typing-extensions  3.10.0.2
urllib3            1.26.6
wheel              0.37.0
zipp               3.5.0
```

**Comment by yzhangcs** [comment]
@unikcc Does the path to the file `ptb/test.conllx` really exist?

**Comment by unikcc** [comment]
@yzhangcs Nope, I'm sorry for my unfamiliar with the code. Then it work fine now!
